{{- with .Values.deployments.console }}
---

# EBSI Portal Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      containers:
        - name: console
          image: {{ .imagePrefix }}{{ .image }}:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          env:
            - name: DATABASE__JDBC_URL
              value: "jdbc:postgresql://postgres:5432/waltid"
            - name: DATABASE__USERNAME
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_USER }}
            - name: DATABASE__PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD }}
            - name: ISSUER__BASE_URL
              value: "https://{{ $.Values.oauthApiHost }}"
            - name: ISSUER__ADMIN_USERNAME
              valueFrom: { secretKeyRef: { name: keycloak-secret, key: ADMIN_USERNAME }}
            - name: ISSUER__ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-secret, key: ADMIN_PASSWORD }}
            - name: WALLET__BASE_URL
              value: "https://{{ $.Values.consoleHost }}/wallet"
            - name: WALLET__REDIRECT_URI
              value: "https://{{ $.Values.consoleHost }}/wallet/auth/callback"
            - name: WALTID__WALLETAPI__BASE_URL
              value: "http://waltid-wallet-api:7001"
          ports:
            - containerPort: 9000
---

# EBSI Portal Service
#
apiVersion: v1
kind: Service
metadata:
  name: console
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app.kubernetes.io/name: console
---

# EBSI Portal IngressRoute
#
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.consoleHost }}")
      kind: Rule
      services:
        - name: console
          port: 9000
  tls:
    secretName: {{ $.Values.tlsSecret }}
---

{{- end }}
