{{- with .Values.deployments.whoami }}

# Whoami Deployment
# https://github.com/traefik/whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      containers:
        - name: whoami
          image: {{ .registry }}traefik/whoami:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          args: [ "--port=8080" ]
          ports:
            - containerPort: 8080

# Whoami Service
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: whoami
---

# Whoami IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ .hostName }}")
      kind: Rule
      services:
        - name: whoami
          port: 8080
  tls:
    secretName: {{ $.Values.tlsSecret }}
---

{{- end }}
