#
# ansible-playbook -i ansible/inventory.yml ansible/step02-kube-config.yml
#
---
- name: Install K3S
  hosts: k3s-server
  become: yes

  tasks:
    -
    # Hostname ---------------------------------------------------------------------------------------------------------

    - name: Get external IP address
      ansible.builtin.shell: "curl -s ipinfo.io/ip"
      register: external_ip

    # Kubectl config ---------------------------------------------------------------------------------------------------

    - name: Copy kubectl config
      ansible.builtin.shell:
        cp /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s-{{ kube_context }}.yaml
      register: copy_kube_config

    - name: Copy kubectl config result
      ansible.builtin.debug:
        var: copy_kube_config

    - name: Replace 127.0.0.1 with external IP
      ansible.builtin.shell:
        sed -i "s/127.0.0.1/{{ external_ip.stdout }}/" /etc/rancher/k3s/k3s-{{ kube_context }}.yaml
      register: replace_ip

    - name: Replace 127.0.0.1 result
      ansible.builtin.debug:
        var: replace_ip

    - name: Replace 'default' with {{ kube_context }}
      ansible.builtin.shell:
        sed -i "s/default/{{ kube_context }}/" /etc/rancher/k3s/k3s-{{ kube_context }}.yaml
      register: replace_default

    - name: Replace 'default' result
      ansible.builtin.debug:
        var: replace_default

    - name: Fetch kubectl config from remote server
      fetch:
        src: /etc/rancher/k3s/k3s-{{ kube_context }}.yaml
        dest: "{{ playbook_dir }}/"
        flat: yes
      register: fetch_kube_config

    - name: Merge kube config files
      local_action:
        module: shell
        cmd: |
          kubectl config delete-context {{ kube_context }} || true \
          && kubectl config delete-cluster {{ kube_context }} || true \
          && kubectl config delete-user {{ kube_context }} || true \
          && KUBECONFIG=~/.kube/config:{{ playbook_dir }}/k3s-{{ kube_context }}.yaml \
            kubectl config view --flatten > {{ playbook_dir }}/merged-config.yaml \
          && rm {{ playbook_dir }}/k3s-{{ kube_context }}.yaml \
          && mv merged-config.yaml ~/.kube/config \
          && chmod 600 ~/.kube/config
      register: kubecfg_merge
      become: no

    - name: Merge kube config result
      ansible.builtin.debug:
        var: kubecfg_merge

    - name: Use context {{ kube_context }}
      local_action:
        module: shell
        cmd: kubectl config use-context {{ kube_context }}
      register: kubecfg_use
      become: no

    - name: Use context result
      ansible.builtin.debug:
        var: kubecfg_use.stdout_lines

    - name: Get kube-system pods
      local_action:
        module: shell
        cmd: kubectl get pod -n kube-system
      register: kube_pods
      become: no

    - name: Get pods result
      ansible.builtin.debug:
        var: kube_pods.stdout_lines
