#
# helm upgrade --kube-context=ebsi --install nessus-identity ./helm -f ./helm/values-services-stage.yaml
#
environment: stage

# WebApp Services
#
consoleHost: "console.nessustech.io"
ebsiPortalHost: "ebsi.nessustech.io"

# Services
#
oauthApiHost: "oauth.nessustech.io"

# WaltId Services
#
waltidWalletApiHost: "waltid-wallet-api.nessustech.io"
waltidDemoWalletHost: "waltid-wallet-demo.nessustech.io"
waltidDevWalletHost: "waltid-wallet-dev.nessustech.io"

# Origin Certificate from Cloudflare
#
tlsSecret: origin-tls

deployments:

  # SQL Service
  #
  postgres:
    version: 17.4
    nodePort: 32543

  # OAuth Service
  #
  keycloak:
    version: nightly
    pullPolicy: Always

  # Nessus Services
  #
  console:
    imagePrefix: "registry.vps4c.eu.ebsi:30443/"
    image: "nessusio/console"
    version: latest
    pullPolicy: Always

  # WaltId Services
  #
  waltid_wallet_api:
    imagePrefix: "registry.vps4c.eu.ebsi:30443/"
    image: "waltid-wallet-api"
    version: 1.0.0-SNAPSHOT
    pullPolicy: Always
  waltid_demo_wallet:
    image: "waltid/waltid-demo-wallet"
    version: latest
    pullPolicy: Always
  waltid_dev_wallet:
    image: "waltid/waltid-dev-wallet"
    version: latest
    pullPolicy: Always
