#
# helm upgrade --kube-context ebsi --install whoami ./helm -f ./helm/values-whoami-stage.yaml
#
environment: stage

tlsSecret: origin-tls

deployments:
  whoami:
    version: latest
    # registry: "registry.nessustech.io/"
    hostName: who.nessustech.io

